---
# tasks file for criecm.ctld

- name: 'zfs vol {{ z.path }}'
  zfs:
    name: '{{ z.path | replace("/dev/zvol/","") }}'
    extra_zfs_properties:
      volsize: '{{ z.volsize }}'
    state: present
  loop: '{{ iscsi_targets | json_query(jq) | flatten(levels=1) | selectattr("path","match","^/dev/zvol") | list }}'
  loop_control:
    loop_var: z
  vars:
    jq: "*.luns.*.{path: path, volsize: volsize}"
  when: z.volsize | default(False)
  notify: reload ctld

- name: ctl.conf template
  template:
    src: '{{ item }}'
    dest: /etc/ctl.conf
    backup: yes
#    force: no
  with_first_found:
    - 'templates/{{ inventory_hostname }}/ctl.conf.j2'
    - 'files/{{ inventory_hostname }}/ctl.conf.j2'
    - 'templates/ctl.conf.j2'
  notify: reload ctld
  tags: iscsi, config

- name: enable ctld
  service:
    name: ctld
    state: started
    enabled: yes
  tags: iscsi, config
