---
# tasks file for criecm.ctld

- name: zfs vol
  include_role:
    name: criecm.zfs
    tasks_from: zfs.yml
  vars:
    jq: "*.luns.*.{path: path, origin: origin, volsize: volsize}"
    zfs:
      zfsrc: '{{ z.path | replace("/dev/zvol/","") }}'
      origin: '{{ z.origin | default(omit) }}'
      volsize: '{{ z.volsize | default(omit) }}'
  loop: '{{ iscsi_targets | json_query(jq) | flatten(levels=1) | selectattr("path","match","^/dev/zvol") | list }}'
  loop_control:
    loop_var: z
  when: z.origin | default("") | length > 0 or z.volsize | default("") | length > 0

- name: ctl.conf template
  template:
    src: '{{ item }}'
    dest: /etc/ctl.conf
    backup: yes
#    force: no
  with_first_found:
    - 'templates/{{ inventory_hostname }}/ctl.conf.j2'
    - 'files/{{ inventory_hostname }}/ctl.conf.j2'
    - 'templates/ctl.conf.j2'
  notify: reload ctld
  tags: iscsi, config

- name: enable ctld
  service:
    name: ctld
    state: started
    enabled: yes
  tags: iscsi, config
