---
# tasks file for criecm.ctld

- name: fail if needed
  fail:
    msg: "origin is not a snapshot or volsize doesn't match [0-9]+[MGT] for iscsi id {{ y.id }}"
  loop: '{{ iscsi_targets | json_query(iscsi_json_query) | flatten(levels=1) | selectattr("path","match","^/dev/zvol") | list }}'
  loop_control:
    loop_var: y
  when: ( y.origin is defined and y.origin and y.origin is not search("@") ) or ( y.volsize is defined and y.volsize and y.volsize is not match("[0-9]+[MGT]") )

- name: zfs vol
  include_role:
    name: criecm.zfs
    tasks_from: zfs.yml
  vars:
    onezfs:
      zfsrc: '{{ z.path | replace("/dev/zvol/","") }}'
      origin: '{{ z.origin | default(omit) }}'
      volsize: '{{ z.volsize | default(omit) }}'
  loop: '{{ iscsi_targets | json_query(iscsi_json_query) | flatten(levels=1) | selectattr("path","match","^/dev/zvol") | list }}'
  loop_control:
    loop_var: z
  when: ( z.origin is defined and z.origin and z.origin is search("@") ) or ( z.volsize is defined and z.volsize and z.volsize is match("[0-9]+[MGT]") )

- name: ctl.conf template
  template:
    src: '{{ item }}'
    dest: /etc/ctl.conf
    backup: yes
#    force: no
  with_first_found:
    - 'templates/{{ inventory_hostname }}/ctl.conf.j2'
    - 'files/{{ inventory_hostname }}/ctl.conf.j2'
    - 'templates/ctl.conf.j2'
  #notify: reload ctld
  tags: iscsi, config

#- name: enable ctld
#  service:
#    name: ctld
#    state: started
#    enabled: yes
#  tags: iscsi, config
